module.exports = {
  abbrevToFull: {
    "ACC": "Accounting Major",
    "ACT": "Actuarial Science Major",
    "ART": "Arts Administration Major",
    "AAAS": "Asian and Asian American Studies Major",
    "BCOM": "Business Communications Major",
    "BIO": "Biological Sciences Major",
    "CIS": "CIS Major",
    "COMS": "Communication Studies Major",
    "ECO": "Economics Major",
    "ENG": "English Major",
    "FIN": "Finance Major",
    "HIS": "History Major",
    "FINM": "Financial Mathematics Major",
    "IOP": "IO Psych Major",
    "INTB": "International Business Major",
    "JRN": "Journalism Major",
    "MGT": "Management Major",
    "MKT": "Marketing Major",
    "MTH": "Math Major",
    "MSC": "Music Major",
    "PHI": "Philosophy Major",
    "PHY": "Physics Major",
    "POL": "Political Science Major",
    "PSY": "Psychology Major",
    "PAF": "Public Affairs Major",
    "QMM": "QMM Major",
    "RES": "Real Estate Major",
    "SQM": "SQM Major",
    "SOC": "Sociology Major",
    "STA": "Statistics Major",
    "UNDECIDED": "Major Undecided",
  },
  fullToAbbrev: {
    "Accounting Major": "ACC",
    "Actuarial Science Major": "ACT",
    "Arts Administration Major": "ART",
    "Asian and Asian American Studies Major": "AAAS",
    "Business Communications Major": "BCOM",
    "Biological Sciences Major": "BIO",
    "CIS Major": "CIS",
    "Communication Studies Major": "COMS",
    "Economics Major": "ECO",
    "English Major": "ENG",
    "Finance Major": "FIN",
    "History Major": "HIS",
    "Financial Mathematics Major": "FINM",
    "IO Psych Major": "IOP",
    "International Business Major": "INTB",
    "Journalism Major": "JRN",
    "Management Major": "MGT",
    "Marketing Major": "MKT",
    "Math Major": "MTH",
    "Music Major": "MSC",
    "Philosophy Major": "PHI",
    "Physics Major": "PHY",
    "Political Science Major": "POL",
    "Psychology Major": "PSY",
    "Public Affairs Major": "PAF",
    "QMM Major": "QMM",
    "Real Estate Major": "RES",
    "SQM Major": "SQM",
    "Sociology Major": "SOC",
    "Statistics Major": "STA",
    "Major Undecided": "Undecided",
  }
};
